language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
install:
  - pip install -r requirements.txt
  - pip install https://cdn.mysql.com/Downloads/Connector-Python/mysql-connector-python-2.1.3.tar.gz
script: nosetests
branches:
  only:
    - master
